// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbqvp6gAt6HV7XYZKo1Urunh67V_wMX6E',
    appId: '1:246958515185:web:c7b5a7cbbced64aa0e9a50',
    messagingSenderId: '246958515185',
    projectId: 'my-app-9e320',
    authDomain: 'my-app-9e320.firebaseapp.com',
    storageBucket: 'my-app-9e320.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiF0EM92Qx_MawK8XD1hUh6kfLNNMx81c',
    appId: '1:246958515185:android:c25c23ea1cb2f0da0e9a50',
    messagingSenderId: '246958515185',
    projectId: 'my-app-9e320',
    storageBucket: 'my-app-9e320.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9D-0c1Y4HvDc-tRAqRLJ8DiNFmaDHC_Y',
    appId: '1:246958515185:ios:6a0398861f98342a0e9a50',
    messagingSenderId: '246958515185',
    projectId: 'my-app-9e320',
    storageBucket: 'my-app-9e320.firebasestorage.app',
    iosBundleId: 'com.example.medical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9D-0c1Y4HvDc-tRAqRLJ8DiNFmaDHC_Y',
    appId: '1:246958515185:ios:6a0398861f98342a0e9a50',
    messagingSenderId: '246958515185',
    projectId: 'my-app-9e320',
    storageBucket: 'my-app-9e320.firebasestorage.app',
    iosBundleId: 'com.example.medical',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbqvp6gAt6HV7XYZKo1Urunh67V_wMX6E',
    appId: '1:246958515185:web:3c7448c2a9b99a6e0e9a50',
    messagingSenderId: '246958515185',
    projectId: 'my-app-9e320',
    authDomain: 'my-app-9e320.firebaseapp.com',
    storageBucket: 'my-app-9e320.firebasestorage.app',
  );
}
